### ISSUE TITLE
assigning issue

### ISSUE THREAD

**Issue by sb39** [UdacityFrontEndScholarship/jeevan-rakht#104]
please assign tasks to specific person @admins, all are working on one issue, you should allocate an issue to almost two people,  rest gets demotivated if their pull is not merged. Look into the issue, please.

**Comment by strongSoda** [comment]
Hi @sb39 

We can assign issues to specific people , which we will do for certain specific issues, but we can't limit all the issues to specific people as to record contribution of participants it is necessary to make PRs and we have less issues compared to the participants contributing. And as this is important for selection of second phase, we want to give everyone opportunities.

And we will assign specific tasks when we come to those.

Imran Mod @JeevanRakht
