### ISSUE TITLE
Issue-14: Server: Check and save donor details 

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/jeevan-rakht#141]
The next task at back-end is to test the functionalities of donate page.
**Step-1** User registered on jeevanrakht
**Step-2** User clicks on donate button, he will be taken to the donar profile page for filling up the further details needed for a donor. 

**route file:(back-end code)** routes/profile/users.js
**html file(donar profile page)** routes/profile/users.hjs

You can refer to the below section of the wireframe attached in README file.
![image](https://user-images.githubusercontent.com/15084301/39352984-093a413c-4a24-11e8-9733-2ded0ffe5445.png)
The templates will be ready to start working and contributing so stay tuned and DM me or @sujan-patel for more details.

**Deadline: 5 May, 2018**

**Comment by gauravsinghaec** [comment]
Template for donor/profile form is created.

**Comment by manasasravanthi96** [comment]
Hi,
I would like to do on this issue, Of collecting more details from the person in front-end.

**Comment by gauravsinghaec** [comment]
This template is done, please check the issue 15 @manasasravanthi96

**Comment by gauravsinghaec** [comment]
The task is completed and we are able to save user's aka donor's details in MongoDB.
