### ISSUE TITLE
Issue-15: Server: Find and list the donor based on search criteria on locate page

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/jeevan-rakht#142]
The next task at back-end is to test the functionalities of donate page.
**Step-1** Either a registered or new user can locate donors on jeevanrakht.
**Step-2** User clicks on locate button, he will be taken to the locate page. Then search and list donors based on the selection criteria. 
Donorlist page URL: https://jeevanrakht.herokuapp.com/donarlist
If you are a registered user you can see detailed list with donor names & other info otherwise you will see only the basic details like number of blood units available.
**route file:(back-end code)** routes\main\donarlist.js
**html file(donarlist page)** views\main\donarlist.hjs 

Check the locate blood State-B and State-C mockups in below path: 
https://github.com/gauravsinghaec/jeevan-rakht/tree/master/_workables/UI/WebApp

You can refer to the below section of the wireframe attached in README file.
![image](https://user-images.githubusercontent.com/15084301/39356074-bfc45a8e-4a2c-11e8-8864-44e6dd07f668.png)

The templates will be ready to start working and contributing. So stay tuned and DM me or @sujan-patel for more details.

**Comment by manasasravanthi96** [comment]
I would like to take part in this issue, of locate blood.

**Comment by gauravsinghaec** [comment]
@manasasravanthi96 yes please work on the UI part and make sure the page appearance(styles and javascripts) are in sync with other pages. check existing pages and css class(app.css) for help. You can ping me or @nsaicharan for any help

**Comment by manasasravanthi96** [comment]
Hello gauravsingh,
I have implemented this if it requires more addition design please give me suggestions to make this more effective.
![capture3](https://user-images.githubusercontent.com/36622595/39917779-36bd13e2-552c-11e8-86b4-465b2efac9bc.PNG)

**Comment by gauravsinghaec** [comment]
@manasasravanthi96 please raise the PR with this template.

**Comment by gauravsinghaec** [comment]
**Locate page functionalities implemented**
* User will see only donors counts when he/she is not signed in
* User will see the donors details when he/she is signed in
  - Locate search won't count the signed in user for the donor list

**Locate page pending functionalities *
* Filter results base on search criteria
* User will see the donors details when he/she is signed in
  - Need to implement contact donor functionality

**Comment by gauravsinghaec** [comment]
**Completed filter functionalities to find donors based on:**
Blood Group
Availability Date
Location(City)

**Locate page pending functionalities**
* Need to implement contact donor functionality(User will see the donors list in locate search results when he/she is signed in and will be able to connect with them)

**Comment by gauravsinghaec** [comment]
**Completed functionality:**
 -  Contact Donor
User logged in, went to locate page and searched for donors:
**Donor list on locate page:**
![image](https://user-images.githubusercontent.com/15084301/40474399-88f27f5a-5f5c-11e8-85fe-0f5ad1a01c64.png)

Now if you want to contact a particular donor then click on contact as shown above. 
**Below is the confirmation screen before we send the visitor's(logged in user) details to the selected donors:** 
![image](https://user-images.githubusercontent.com/15084301/40474492-d30ffacc-5f5c-11e8-8c0c-3d675bbaee42.png)

**Once you confirm, a mail from jeevanrakht will be sent to the donors and user will be redirected to Locate Page with an alert message as shown below:**
![contact_donar_success](https://user-images.githubusercontent.com/15084301/40474658-3fae7294-5f5d-11e8-9e2c-7ac7cd7d5e1e.JPG)

**Email Content (Received by donor ):**
![image](https://user-images.githubusercontent.com/15084301/40475145-73c75e28-5f5e-11e8-9a7b-94e8bd70b34a.png)

@viditkothari @strongSoda @Soumya44 @utkarsh2102 @mcashashankkumar @sujan-patel @Hardiki 
Please check and validate the functionality as the code is deployed on Heroku:
https://jeevanrakht.herokuapp.com/locate

**Comment by gauravsinghaec** [comment]
Task accomplished.
