### ISSUE TITLE
Redesigning Footer 

### ISSUE THREAD

**Issue by utkarsh2102** [UdacityFrontEndScholarship/jeevan-rakht#145]
The Footer needs to be redesigned with the the given Font Awesome images.
@Soumya44 : Can you fix it back please?
Or anyone who wants to claim it?

**Comment by seethaR03** [comment]
Can you show the preview of resdesigned footer?

**Comment by raj-abhishek** [comment]
I can help in redesigning the footer!

**Comment by utkarsh2102** [comment]
Please do and make a PR of the same.

**Comment by Kundan28** [comment]
I can help too...

**Comment by Kundan28** [comment]
I have made PR for the same...

**Comment by Logan1x** [comment]
you would have been seeing your username instead of mine if you did that...

![image](https://user-images.githubusercontent.com/10944610/39523018-dc6c7474-4e31-11e8-8777-9fa9ffeb5930.png)

**Comment by Kundan28** [comment]
I have changed the title from Redesigned Footer with the Font Awesome images. to #145 Redesigned Footer with the Font Awesome images.

**Comment by Kundan28** [comment]
Should I remove #145 from the title ?

**Comment by Logan1x** [comment]
it's totally your choice. its another way of tracking but if someone visiting this issue and find the reference link it would help them more rather then finding all the open/closed issue.

**Comment by Kundan28** [comment]
Okay...
