### ISSUE TITLE
Redesign Header for Homepage.

### ISSUE THREAD

**Issue by Logan1x** [UdacityFrontEndScholarship/jeevan-rakht#160]
The header is poorly designed & need to be redesigned for [Homepage](https://jeevanrakht.herokuapp.com/index.html).
![selection_023](https://user-images.githubusercontent.com/10944610/39522441-cea280ba-4e2f-11e8-97c3-488c105cf15d.png)

**Comment by viditkothari** [comment]
@Logan1x Thanks for your valuable feedback. We are currently in-process of some design overhaul. Will let the community know of the updates soon. :)

**Comment by Logan1x** [comment]
does that mean the whole home will be redesigned and the error will be solved too? @viditkothari

**Comment by viditkothari** [comment]
@Logan1x We are reviewing content update , only after which will we be able to confirm anything
