### ISSUE TITLE
Back  button is not working 

### ISSUE THREAD

**Issue by Logan1x** [UdacityFrontEndScholarship/jeevan-rakht#161]
![selection_024](https://user-images.githubusercontent.com/10944610/39523556-b15a831e-4e33-11e8-843f-48f4c880ee06.png)
Back button is not working on https://jeevanrakht.herokuapp.com/locate

**Comment by gauravsinghaec** [comment]
Thanks @Logan1x yeah, we are fixing it in next drop along with other design changes to make it consistent with other page.

**Comment by Logan1x** [comment]
assign me this issue i would work on that

**Comment by gauravsinghaec** [comment]
@Logan1x great, there are few more things to add. Please check the /donate and try to add margin-top / bottom and also adjust the width as per the footer. Go through the /donate and DM me for further assistance.

**Comment by Logan1x** [comment]
Sure I'll try to help as much as I can

**Comment by Logan1x** [comment]
hey, @gauravsinghaec I am not able to figure out where do I need to change, can you guide me. I checked js files of locate and donate but both are similar.

**Comment by Logan1x** [comment]
the issue is solved by someone but I still want to know where do I need to change.
