### ISSUE TITLE
website name is missing in mobile view.

### ISSUE THREAD

**Issue by sskanishk** [UdacityFrontEndScholarship/jeevan-rakht#168]
https://jeevanrakht.herokuapp.com/index.html
![screen shot 2018-05-04 at 1 14 32 am](https://user-images.githubusercontent.com/29313203/39599722-37f112ec-4f3a-11e8-9aa4-935cd5487ef5.png)

**Comment by utkarsh2102** [comment]
Will be taken care of. Do let us know if it is still missing.
