### ISSUE TITLE
Vertical scroll list is not responsive.

### ISSUE THREAD

**Issue by Kundan28** [UdacityFrontEndScholarship/jeevan-rakht#169]
https://jeevanrakht.herokuapp.com/index.html
![vertical scroll list](https://user-images.githubusercontent.com/33788217/39612276-aa745c70-4f7b-11e8-9cc1-6e80fd1ba7e1.jpg)
The size of the headlines remain same even for the devices having smaller screen size.

**Comment by utkarsh2102** [comment]
Hi @Kundan28,
The website is being redesigned now.
Please help us in the same.
