### ISSUE TITLE
Nav Bar 

### ISSUE THREAD

**Issue by sumilmehta** [UdacityFrontEndScholarship/jeevan-rakht#173]
The nav bar on your know more page is not properly aligned. The done button has zero top margin, the search bar is not responsive

![capture](https://user-images.githubusercontent.com/18137211/39661295-c99f8e84-506c-11e8-8f08-9802079d25ef.JPG)

**Comment by vamsikrishnareddybevara** [comment]
hi sumil mehta...  i already  mentioned this problem..and i'm working on it...

**Comment by sumilmehta** [comment]
The other issue just pointed out the search button only.

**Comment by vamsikrishnareddybevara** [comment]
yes..i am working on that also..can i/

**Comment by utkarsh2102** [comment]
Hi @sumilmehta,
The website is being redesigned now.
Please help us in the same.
