### ISSUE TITLE
Extra Margin/ White Space at bottm

### ISSUE THREAD

**Issue by sumilmehta** [UdacityFrontEndScholarship/jeevan-rakht#177]
There is some margin after the footer/social media links division. 
![capture](https://user-images.githubusercontent.com/18137211/39662734-2c4f08c2-5084-11e8-9dd8-d8d0e5d86c51.JPG)

**Comment by utkarsh2102** [comment]
Hi @sumilmehta,
The website is being redesigned now.
Please help us in the same.
