### ISSUE TITLE
Issue 17: (Frontend - JavaScript)Signup Page: Implement smart form validation using JavaScript or jQuery.

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/jeevan-rakht#181]
Now all the validation happens at server side but as you all know its unnecessary to send HTTP request to server before validating input values at the client side. We have kept pretty simple validation as of now and hope you will gain more hands on on JS by working on this issue:
Validate form on click of **save** (event handler using JS) button or validate **on change** event as user types in a value in the field.

**HTML File: views/auth/signup.hjs**

**Field Name** | **Validation Criteria**
First Name  |  first name must contain minimum 3 chars
Last Name  |  last name must contain minimum 3 chars
Bank Name  |  bank name must contain minimum 3 chars
License Name  |  license name must contain minimum 3 chars
Password  |  password must contail one capital & one small letter with total six chars min.
Confirm Password |  Both passwords should match

Page URL: https://jeevanrakht.herokuapp.com/signup

![image](https://user-images.githubusercontent.com/15084301/39666000-414426be-50ba-11e8-8fa5-7e5deba11d3e.png)

Please feel free to reach **jeevanrakht** team for any help.
Happy Coding.....

**Comment by abhishekakade** [comment]
I'd like to work on this one.

**Comment by gauravsinghaec** [comment]
@abhishekakade Please go ahead and share the working link for review before raising the PR.

**Comment by skywalker212** [comment]
I am working on this issue.

**Comment by gauravsinghaec** [comment]
Task completed. @abhishekakade @skywalker212 🥇
