### ISSUE TITLE
can i know why the main.css file is removed?

### ISSUE THREAD

**Issue by vamsikrishnareddybevara** [UdacityFrontEndScholarship/jeevan-rakht#182]
![screenshot 189](https://user-images.githubusercontent.com/38369869/39666012-6e7ca5f2-50ba-11e8-8a33-76af7eddd1ef.png)
why the main.css is removed?

**Comment by utkarsh2102** [comment]
Because the whole website is being redesigned. I'll add the empty one meanwhile.
