### ISSUE TITLE
Route issue on home page

### ISSUE THREAD

**Issue by mohit94614** [UdacityFrontEndScholarship/jeevan-rakht#183]
Home page requesting for  following url 
https://jevanrakth.herokuapp.com/login.html
404 Error 

![image](https://user-images.githubusercontent.com/17672906/39666087-77f21e9a-50bb-11e8-93f0-1eade9ea17e7.png)

**Comment by gauravsinghaec** [comment]
1. Its old version of code. Update the repo with latest code.
https://jeevanrakht.herokuapp.com/-- Our official App URL
2. We don't have login.html, signup.html or profile.html static pages rather you can find those pages on webapp
**Login :** https://jeevanrakht.herokuapp.com/login
**Signup :** https://jeevanrakht.herokuapp.com/signup
**Profile :** https://jeevanrakht.herokuapp.com/users
