### ISSUE TITLE
Locate Blood or Donate Blood page Should have Map at the bottom

### ISSUE THREAD

**Issue by mmnauman** [UdacityFrontEndScholarship/jeevan-rakht#185]
Hello, I have noticed that we should have the map that should show where is the blood available in the city entered by the user. and when the user wants to donate it should show on the map the name that can be easily selected.

![github issue](https://user-images.githubusercontent.com/23205151/39672413-45db61f0-5147-11e8-90bb-b36c3b1eb141.JPG)

**Comment by viditkothari** [comment]
Hi @mmnauman, yes indeed it should but in later phase of development. We have limited the current scope of development. 

Thanks for suggesting though!
