### ISSUE TITLE
Password Update issue

### ISSUE THREAD

**Issue by mmnauman** [UdacityFrontEndScholarship/jeevan-rakht#190]
Hello, When I have logged correctly and want to change or update my password through my profile. It is taking me to the forgot password page why? It should give the direct option to update the password after some sort of captcha verifying. Please fix this.
![project issue google](https://user-images.githubusercontent.com/23205151/39707420-fe7cd1d6-5231-11e8-9e40-12f0e30ea124.PNG)

**Comment by mmnauman** [comment]
I have a solution to it. We just need to display the input box option and above a captcha that should be like random number + random number then after verifying we can change the password through our profile section. Hope you got it

**Comment by gauravsinghaec** [comment]
Sorry @mmnauman but this is not an issue rather suggestion. It's not only for logged in user rather even at login page for forgot password. You will be getting unique reset link to reset the password and that link is temporary.
You can though implement and share your code repo for learning. 
But this is the implementation of the current phase. Thanks for your suggestion. Do let us know if you are getting issue in updating your password?
