### ISSUE TITLE
Prepare • Format • Proof read the content document.

### ISSUE THREAD

**Issue by viditkothari** [UdacityFrontEndScholarship/jeevan-rakht#191]
We need the content document ready for further processing.

Please check the original document and the partly-edited document (formatted in a way that we need our document to be.) in the:

1. https://github.com/UdacityFrontEndScholarship/jeevan-rakht/blob/master/_workables/content/JeevanRakht%20Information_v1.docx & 

1. https://github.com/UdacityFrontEndScholarship/jeevan-rakht/blob/master/_workables/content/JeevanRakht%20Information_v2.docx

The *only difference as of now is that of formatting*, but it is not complete.

What we expect to do is, get this document ready with the content properly documented *according to the navigation and site structure that we have decided*.

Three things to make sure:
1) Content is well arrange under proper heading / section
2) Font used are: Montserrat and Spectral
3) They can use my document to do carry on the editing job

**Comment by viditkothari** [comment]
Hi @seethaR03 , can you please check now?

**Comment by seethaR03** [comment]
Yeah it works

**Comment by sumilmehta** [comment]
@viditkothari  

1. Every 3 Month**s**  (page 1)
2. Your blood **can** save a life (page 2)
3. details **like** blood group, location **etc** (page 2)

A lot of places with missing articles and wrong use of spaces(and commas).

**Comment by seethaR03** [comment]
Is this issue still open?

**Comment by viditkothari** [comment]
@seethaR03 yes, but since we didn't receive support on time, I'll close this in few hours

**Comment by viditkothari** [comment]
@sumilmehta, I am unable to find mentioned textual occurrences on page 23

**Comment by viditkothari** [comment]
@sumilmehta 
thanks. Got it :)
