### ISSUE TITLE
Location and validation error's

### ISSUE THREAD

**Issue by mohit94614** [UdacityFrontEndScholarship/jeevan-rakht#195]
![image](https://user-images.githubusercontent.com/17672906/39771078-9769fe78-530e-11e8-8705-c2a14cc76cee.png)
Autolocation Can't detect first line of address such that in auto detection by gps it's not allowing the user to enter by manual and generating validation error

Validation of Weight and height Should Also be done

**Comment by gauravsinghaec** [comment]
You can edit the address by selecting the edit radio button if you didn't get proper GPS address.

**Comment by mohit94614** [comment]
i can select the radio button but the users using the application won't be so smart like all of us working on the project the don't know that he/she can do that using radio button maybe few can find out .
in certain Cases the GPS don't work properly .

**Comment by gauravsinghaec** [comment]
Closing this as it is expected as per current design and we will look into it in next cycle of development.
We are going to conduct a demo session for jeevanrakht app.
