### ISSUE TITLE
Issue 18: (App Frontend)Profile Page Validation: Implement smart form validation using RegEx, JavaScript or jQuery at client side.

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/jeevan-rakht#197]
Now all the validation happens at server side but as you all know its unnecessary to send HTTP request to the server before validating input values at the client side. We are opening another issue for form validation at the client side. Validate form on click of **save** (event handler using JS) button or validate **on change** event as user types in a value in the field. Please check the pretty simple validation that you need to implement in each field as listed below:
**File: views/profile/users.hjs**

**Field Name | Validation Criteria**
Bank Name | bank name must contain minimum 3 chars
License Name | license name must contain minimum 3 chars  

First Name | first name must contain minimum 3 chars
Last Name | last name must contain minimum 3 chars

Address Line1 | Address line1 is required and first letter can\'t be a special character.
Address Line2 | Address line2 is required and fist letter can\'t be a special character.
City | city must contain only alphabets and spaces.
State | state must contain only alphabets and spaces.
Pincode | zip must be a 6 digit number.'       

Page URL: https://jeevanrakht.herokuapp.com/users

![image](https://user-images.githubusercontent.com/15084301/39796321-829e16ea-5373-11e8-9721-4c1b89c0af4d.png)

You can use RegEx wherever required.

Please feel free to reach jeevanrakht team for any help.
Happy Coding.....

**Comment by skywalker212** [comment]
@gauravsinghaec can i work on this, I will also work on isuue #181 and #198

**Comment by gauravsinghaec** [comment]
@skywalker212 you are always welcome to work on the issues and yes please comment on the other issues as well before working on it. It will help others to know who all are working.
Do share the link on issues before raising the PR. 
All the best.

**Comment by skywalker212** [comment]
okay, thanks!

**Comment by skywalker212** [comment]
solved this issue
my local commit: https://github.com/skywalker212/jeevan-rakht/commit/6c022cc38a4c7ab5b722c7905ccd65860772067d
heroku deployment: https://morning-headland-57135.herokuapp.com/users

**Comment by gauravsinghaec** [comment]
@skywalker212 One suggestion (It applies to your earlier signup, donate too) like can you keep else if check otherwise now it is stacking all the alerts one above other and you need to close all the alerts before you can proceed. Either we can show all alerts at once as a list (which may not look good) or trigger one alert at a time.(like if... else if  .... else if).

**Comment by skywalker212** [comment]
okay then ill do else if so only one alert displays at a time

**Comment by skywalker212** [comment]
@gauravsinghaec updated code to display one alert at a time, added a minimum count of 0 in bloodstock for the organization.
https://github.com/skywalker212/jeevan-rakht/commit/a6080f40ad974894ca7037cd0c3bdf22b7972af4
heroku: https://morning-headland-57135.herokuapp.com/users

**Comment by gauravsinghaec** [comment]
@skywalker212 awesome. Please go ahead and raise the PR and mention this issue number in that.

**Comment by gauravsinghaec** [comment]
Thanks for your effort @skywalker212  🥇 
Closing the issue as it is completed.
