### ISSUE TITLE
Issue 19: (Frontend)Donate Page Validation: Implement smart form validation using RegEx, JavaScript or jQuery at client side.

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/jeevan-rakht#198]
Now all the validation happens at server side but as you all know its unnecessary to send HTTP request to the server before validating input values at the client side. We are opening another issue for form validation at the client side. Validate donate form on click of book (event handler using JS) button or validate on change event as user types in a value in the field. Please check the pretty simple validation that you need to implement in each field as listed below:
File: views/main/donate.hjs

**Field Name | Validation Criteria**
City | city must contain only alphabets and spaces.

Page URL: https://jeevanrakht.herokuapp.com/donate
![image](https://user-images.githubusercontent.com/15084301/39796508-7a6f2652-5374-11e8-9e07-ebad691211f5.png)
You can use RegEx wherever required.

Please feel free to reach jeevanrakht team for any help.
Happy Coding.....

**Comment by skywalker212** [comment]
I am working on this issue

**Comment by gauravsinghaec** [comment]
@skywalker212 Please share the link of your working site/code before raising the PR. Check the contribution guidelines.

**Comment by skywalker212** [comment]
I have solved issue #181 and #198 and my local commit is [here](https://github.com/skywalker212/jeevan-rakht/commit/188a943a8c8cb323f00691e370d5e8b77d11fabe)
can I raise a PR now?

**Comment by gauravsinghaec** [comment]
@skywalker212  If you have deployed the code on Heroku then please share the Heroku link to test the changes.

**Comment by skywalker212** [comment]
https://morning-headland-57135.herokuapp.com
@gauravsinghaec here is the deployed heroku link

**Comment by nsaicharan** [comment]
@skywalker212 
One small suggestion: whitespace is also considered as a character, so after checking the length of fname, lname, etc.,  do another check to see if there are any whitespaces (or numbers).

**Comment by skywalker212** [comment]
@nsaicharan okay,
shall I trim the trailing whitespaces and then check?

**Comment by nsaicharan** [comment]
@skywalker212 yes, that's right.

**Comment by skywalker212** [comment]
@nsaicharan @gauravsinghaec I have updated the code to check for whitespace and numbers.
link to my local commit: https://github.com/skywalker212/jeevan-rakht/commit/5f5c7d2cf9c5c1303e2d660ca7b4e7f984b5d537
heroku: https://morning-headland-57135.herokuapp.com/signup

**Comment by skywalker212** [comment]
@gauravsinghaec you mean that I check for all the errors parallelly and then display them in one alert box right? e.g length of fname and lname must be more than 3 etc.
and I will write functions for checking fields individually, like checkPassword, checkLength etc.

**Comment by gauravsinghaec** [comment]
@skywalker212 I am ok with sequential checks as well but it should validate one field completely before moving to another. For 2nd point yes you are right, general methods which improve the code visibility as well as maintainability.

**Comment by skywalker212** [comment]
@gauravsinghaec I didn't get that, can you give me an example where it fails to do sequential check?
thanks!

**Comment by skywalker212** [comment]
@gauravsinghaec okay, working on it.
Thanks!

**Comment by gauravsinghaec** [comment]
Well done @skywalker212. 🥇  Task completed
