### ISSUE TITLE
[FrontEnd] Designing Footer for the Website.

### ISSUE THREAD

**Issue by utkarsh2102** [UdacityFrontEndScholarship/jeevan-rakht#202]
The Footer needs to be designed as per the given mockup.
[Refer](https://github.com/UdacityFrontEndScholarship/jeevan-rakht/blob/master/_workables/UI/Website/JeevanRakht%20Website_v1%20(draft).jpg).
Please make sure the design is exactly the same as given there.
All the coding should be done in "index.html" file.
Let me know who is up for the task?

**Comment by abhishekakade** [comment]
By tomorrow?

**Comment by mmnauman** [comment]
Hello, Please count me in.

**Comment by manasasravanthi96** [comment]
Plz verify this and give me feedback.
You can DM me at @Prabhu Manasa
https://github.com/UdacityFrontEndScholarship/jeevan-rakht/issues/142

**Comment by abhishekakade** [comment]
I've already made a pull request @divayg, @manasasravanthi96

**Comment by sumilmehta** [comment]
Is this done?

**Comment by gauravsinghaec** [comment]
@abhishekakade always share the working website link before raising a PR to decrease the chances of delay/rejection of your PR. Request you to follow the guidelines.
https://github.com/UdacityFrontEndScholarship/jeevan-rakht/blob/master/CONTRIBUTING.md

**Comment by abhishekakade** [comment]
@gauravsinghaec yeah sorry, forgot about that. Here's the link - 
https://abhishekakade.github.io/jeevan-rakht/public/index.html

**Comment by gauravsinghaec** [comment]
The PR is merged, hence closing the issue.
