### ISSUE TITLE
Facebook SignIn Not Working

### ISSUE THREAD

**Issue by LtSGoel** [UdacityFrontEndScholarship/jeevan-rakht#206]
when login through the facebook , its open the pop-up,as click on continue, it open the facebook popup, but donot fetch the details of the profile.
I think this issue can be solved by https://github.com/jaredhanson/passport-facebook#readme

**Comment by gauravsinghaec** [comment]
@LtSGoel please refer to the https://github.com/UdacityFrontEndScholarship/jeevan-rakht/blob/master/CONTRIBUTING.md guide to know more about raising and valid issues with all important details needed.

**Comment by gauravsinghaec** [comment]
Closing as the issue didn't have enough data to check.
