### ISSUE TITLE
Geolocation search bar not working correctly

### ISSUE THREAD

**Issue by LtSGoel** [UdacityFrontEndScholarship/jeevan-rakht#207]
as search for a place in the search bar, it just give this is a post request .
not search the places

**Comment by gauravsinghaec** [comment]
@LtSGoel please refer to the https://github.com/UdacityFrontEndScholarship/jeevan-rakht/blob/master/CONTRIBUTING.md guide to know more about raising and valid issues with all important details needed. The issue #142 is already in progress and once done you will get data.
