### ISSUE TITLE
Index.html redirect to some otherpage when click on github logo and no body content.Kindly send the design so that work start

### ISSUE THREAD

**Issue by LtSGoel** [UdacityFrontEndScholarship/jeevan-rakht#208]
<img width="1275" alt="screen shot 2018-05-10 at 1 33 45 pm" src="https://user-images.githubusercontent.com/26035935/39859246-d1985844-5456-11e8-900d-aa4a4f690e09.png">

**Comment by gauravsinghaec** [comment]
@LtSGoel please refer to the https://github.com/UdacityFrontEndScholarship/jeevan-rakht/blob/master/CONTRIBUTING.md guide to know more about raising a valid issue with all important details needed. The notification had already been circulated regarding website redesign. Follow the #cp_jvn_rkht channel to get the latest update.
