### ISSUE TITLE
Make the website mobile responsive.

### ISSUE THREAD

**Issue by strongSoda** [UdacityFrontEndScholarship/jeevan-rakht#224]
The new JeevanRakht website is only for desktop size devices. Your task is to make it user friendly on small screens.

This is the link to current website https://jeevanrakht.herokuapp.com/index.html

**Comment by gauravsinghaec** [comment]
@skywalker212 yes, please share your work once done.

**Comment by skywalker212** [comment]
@gauravsinghaec since #229 is related with this, should I wait for that issue to be fixed? or go ahead since my commit and fix of #229 can cause conflicts.

**Comment by gauravsinghaec** [comment]
@skywalker212 please go ahead. The PR is closed now.

**Comment by skywalker212** [comment]
@gauravsinghaec Okay

**Comment by skywalker212** [comment]
@gauravsinghaec done.
heroku: https://morning-headland-57135.herokuapp.com/index.html

**Comment by strongSoda** [comment]
LGTM

@VIDIT @GAURAV

**Comment by skywalker212** [comment]
@strongSoda you have tagged somebody else by mistake 😅
If it's good to go then I'll raise a PR.

**Comment by viditkothari** [comment]
@skywalker212 
The two things that I approve of in your implementation are:

1. The navigation at the top adjust according to the device's dimension but I don't like that you changed the padding which now results in misaligned navigation menu text and logo (vertical alignment needs to be proper)

1. Funny Myth's image placeholder is adjusting nicely but you have changed the placeholder's size out of proportion.

I disliked seeing other fonts like Helvetica being used instead of Montserrat or Spectral.

There are significant amount of changes which I (personally) think needs to be reverted.
@gauravsinghaec  @strongSoda , what do you think?

@skywalker212 can you fix?

**Comment by skywalker212** [comment]
![morning-headland-57135 herokuapp com_index html iphone 6_7_8 plus](https://user-images.githubusercontent.com/16351685/39994889-4b42ab56-5798-11e8-8020-db4a9aa7fed5.png)
![morning-headland-57135 herokuapp com_index html](https://user-images.githubusercontent.com/16351685/39994890-4bb2c1ac-5798-11e8-8917-6dcb1014e611.png)
@viditkothari thanks for the review!
can you tell me exactly where do i need to make changes? 
and I have made the width of image 100% beacuse it was not scaling nicely in the mobile vesion, should i make that a fixed length?
I didn't change the fonts. I kept them as they were, I just made changes in some classes, divs, margins and padding.
I have attached screenshot for iPhone 6_7_8 Plus and desktop.
Please point me in the right direction.

**Comment by skywalker212** [comment]
**Updated**
https://morning-headland-57135.herokuapp.com/index.html
https://github.com/skywalker212/jeevan-rakht/commit/4271a62c17d6fab0055545ec048d4a5681889b78
@viditkothari please tell me the changes that remain.

**Comment by viditkothari** [comment]
@skywalker212 
![Edit 1](https://user-images.githubusercontent.com/409625/40096740-cced6cce-58ef-11e8-864b-43128977e129.png)
![Edit 2](https://user-images.githubusercontent.com/409625/40096741-cd2462d8-58ef-11e8-9ee9-2cbaccd67be5.png)
![Edit 3](https://user-images.githubusercontent.com/409625/40096742-cd5989fe-58ef-11e8-9459-1bb2b1977977.png)
Please note the changes

and nice work ensuring that font is consistent :)

**Comment by gauravsinghaec** [comment]
@skywalker212 any progress on this?

**Comment by skywalker212** [comment]
@gauravsinghaec sorry I was offline and was not able to work on it since the past few days,
I'll do the updates on the weekend. If that's fine.

**Comment by skywalker212** [comment]
@viditkothari okay, thanks for the improvements!
I'll try to resolve those issues as soon as possible. The thing is, I only optimized the site for specifically some display resolution and not for all the possible resolutions, I'll work on it and give you an update once done.

**Comment by nikki158** [comment]
@viditkothari  Is it resolved? Or is anyone working on this?

**Comment by gauravsinghaec** [comment]
@nikki158 yes @skywalker212 is working on it.
Please wait for his changes.

**Comment by praveen-me** [comment]
Ya, Tell me @gauravsinghaec as I said I also working on it for wait for @skywalker212  PR response.

**Comment by skywalker212** [comment]
I'll finish working on the updates by Sunday.

**Comment by skywalker212** [comment]
@viditkothari @gauravsinghaec I have made the changes as you requested and made the site responsive.
https://morning-headland-57135.herokuapp.com/index.html
https://github.com/skywalker212/jeevan-rakht/commit/7d61ccbd4aedb73095e96e9fd9b476484009be86

**Comment by utkarsh2102** [comment]
@skywalker212, I'm waiting to hear more on this very, very soon.
Please keep us updated. We need to get things done by this weekend.

**Comment by skywalker212** [comment]
@utkarsh2102 I have finished working on it, https://morning-headland-57135.herokuapp.com/index.html
please check it out.

**Comment by strongSoda** [comment]
LGTM

Utkarsh plz review code also and do the needful.

**Comment by gauravsinghaec** [comment]
It's good to go. We can merge it so that other can work keeping this as codebase.

**Comment by gauravsinghaec** [comment]
Kudos @skywalker212 for your work. 💯 
@praveen-me you can check the latest code now and comment on this issue if you find anything.
The code is deployed on Heroku, check our official site:
https://jeevanrakht.herokuapp.com/index.html

**Desktop View:**
![image](https://user-images.githubusercontent.com/15084301/40267203-8a09504c-5b76-11e8-9cb2-4741898c48f5.png)
![image](https://user-images.githubusercontent.com/15084301/40267215-c1ae1ac8-5b76-11e8-9d32-f774c922315a.png)
![image](https://user-images.githubusercontent.com/15084301/40267219-d1137634-5b76-11e8-9411-27b99f1b59e4.png)
![image](https://user-images.githubusercontent.com/15084301/40267209-a96c33aa-5b76-11e8-8fab-adaec0f4baf1.png)

**Mobile View:**
![image](https://user-images.githubusercontent.com/15084301/40267224-f46be724-5b76-11e8-9abc-85f93d9540e9.png)
![image](https://user-images.githubusercontent.com/15084301/40267234-0c1773c0-5b77-11e8-9771-35a161c5aa80.png)
![image](https://user-images.githubusercontent.com/15084301/40267239-1cb4afd6-5b77-11e8-8d26-1732d27cc0e0.png)
![image](https://user-images.githubusercontent.com/15084301/40267243-2ce2fee4-5b77-11e8-90ec-6a8b47560d8e.png)
![image](https://user-images.githubusercontent.com/15084301/40267251-3cb6274c-5b77-11e8-912f-024c31ed1906.png)
