### ISSUE TITLE
Graphics Design for 'Funny Myths Slider'

### ISSUE THREAD

**Issue by viditkothari** [UdacityFrontEndScholarship/jeevan-rakht#228]
We need aesthetically pleasing, sober visual designs for the **Funny Myths** slider

You can refer to ***Myths - Blood Donation*** section in the [Content Doc.](https://github.com/UdacityFrontEndScholarship/jeevan-rakht/blob/master/_workables/content/JeevanRakht%20-%20Content%20Doc%20(final).pdf) for text-copy.

To foster contribution from all of you, and ensure more engagement we are open to receiving draft/concepts if not final designs as we know many aren't well versed with graphic design suites. Still, whatever you do, put your best!

Some design inspirations:
• https://in.pinterest.com/viditkothari/cre8ive/ &
• https://in.pinterest.com/viditkothari/design-inspirations/

***Dimension** : Please download and use the base placeholder template attached. Take note of the safe area*
![template - myth slider design](https://user-images.githubusercontent.com/409625/39965261-2ed5757e-56b3-11e8-8bc6-3aa504ffc6ca.jpg)

Looking forward to find some amazing creative ideas!

**Comment by nehavatsyan** [comment]
![powerpnt_2018-05-13_14-56-01](https://user-images.githubusercontent.com/35574268/39965832-3f9a1b20-56be-11e8-9a2b-0f2cffba7696.png)

kindly view it

**Comment by viditkothari** [comment]
Hi @nehavatsyan , glad to see your prompt contribution.
I like the use of syringe here :)

I have couple of suggestions though:
1) Can you try this same text-copy, with the syringe but in a different setting ?
2) Using **bold** Sans-Serif font like Montserrat / Roboto / Open Sans / Oswald / Bebas Neue for the titles and serif like Playfair, etc. for the text ? **Avoid** using Comic Sans MS.
3) Invert the syringe
4) *Do not* stretch the JeevanRakht logo out of proportion

Thanks & Regards

**Comment by nehavatsyan** [comment]
sir i did not get 1st suggestion , what are you asking for in it ?
rest of the suggestions , i will implement them and show

**Comment by viditkothari** [comment]
@nehavatsyan , I meant can you try coming up with another design / version using same content?

**Comment by nehavatsyan** [comment]
ok sir , i will try

**Comment by nehavatsyan** [comment]
![powerpnt1](https://user-images.githubusercontent.com/35574268/39966913-f1623150-56d0-11e8-87f0-4e2080edaa02.png)
![pp2](https://user-images.githubusercontent.com/35574268/39966916-f8c374f4-56d0-11e8-9ed1-f2040fc8ce08.png)

**Comment by viditkothari** [comment]
Nice concepts that should look better if given nice aesthetics

**Comment by Ruchika30** [comment]
Hi. Then should I work on my graphic, the one above?

**Comment by Ruchika30** [comment]
@viditkothari Can i work on this issue ?

**Comment by viditkothari** [comment]
@nehavatsyan can you upload the source file here?

@Ruchika30 , yeah, please use the text-copy from the content doc and impress us :)

**Comment by nehavatsyan** [comment]
[folder.zip](https://github.com/UdacityFrontEndScholarship/jeevan-rakht/files/2007760/folder.zip)

@viditkothari  GitHub does not supports sending psd files so i put them in this zip folder.

**Comment by viditkothari** [comment]
Thanks @nehavatsyan  :)
