### ISSUE TITLE
Issue-20: (Backend+Frontend): Implement delete account functionality.

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/jeevan-rakht#237]
**Frontend Part**: Add a link on the profile page and show an alert when a user clicks on it to delete the account. If user confirms, a server call is made to delete the account from MongoDB.
* Impacted File: views/profile/users.hjs
*Note: Please add css as per project guidelines.

**Backend Part**: Add request handler to act on the input request and hence delete the account from DB.
* Impacted File: routes/profile/users.js

**Comment by gauravsinghaec** [comment]
Work preview on delete account is as follows:

Delete Account Link on Profile Page
![image](https://user-images.githubusercontent.com/15084301/40219980-3eaf4eda-5a95-11e8-9318-f6991a9f5bbc.png)

Delete Account Modal View on Desktop
![image](https://user-images.githubusercontent.com/15084301/40219935-1e4bef72-5a95-11e8-83c1-606201ad0119.png)

Delete Account Modal View in Mobile
![image](https://user-images.githubusercontent.com/15084301/40219898-fb88746a-5a94-11e8-8d3e-6b000fd34959.png)

@viditkothari @strongSoda @mcashashankkumar @utkarsh2102 let me know if you have any concern.

**Comment by mcashashankkumar** [comment]
Everything is good
From my side.

**Comment by Logan1x** [comment]
Yes delete account feature is definitely needed.

**Comment by viditkothari** [comment]
Just a casual question:
Are we *deleting* the record or are we ***actually deleting*** the record? :P :)

**Comment by Logan1x** [comment]
@vidit try at facdebook they might hire you 😂

Sent through a robotic carrier pigeon at Mach 4 speed.

**Comment by viditkothari** [comment]
@Logan1x , what can I say - I ***love*** data too :D 😁

**Comment by gauravsinghaec** [comment]
@viditkothari hard delete, as shown in the alert message 😁. Wipe off the data completely.

**Comment by Logan1x** [comment]
we can add deactivate option too.

**Comment by viditkothari** [comment]
Indeed @Logan1x  😆

**Comment by gauravsinghaec** [comment]
@Logan1x @viditkothari people use to deactivate the account on social media in special cases which you know. But in jeevanrakht, it is 1 or 0, nothing in between. 😜 In a real scenario, the replicated data can exist very well in ETL tables whereas the record is deleted from transaction table.😆

**Comment by gauravsinghaec** [comment]
Delete account functionality is implemented.  The code is deployed, you can test on the official site.
https://jeevanrakht.herokuapp.com/users

**Comment by gauravsinghaec** [comment]
Issue resolved.
