### ISSUE TITLE
Issue-21: (Backend+Frontend): Show existing booking of donors on donate page.

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/jeevan-rakht#240]
**Frontend Part**: Add section on donate page to show existing booking details.
* Impacted File: views/main/donate.hjs
*Note: Please add css as per project guidelines.
![image](https://user-images.githubusercontent.com/15084301/40160542-9dde3a58-59cb-11e8-97bf-79a9926ebcba.png)

**Backend Part**: Add code to get existing booking details from DB to show up on donate page.
* Impacted File: views/main/donate.js

![image](https://user-images.githubusercontent.com/15084301/40160373-0ef85ef4-59cb-11e8-9f3c-b2ac22085f26.png)

**Comment by gauravsinghaec** [comment]
**Updated donate page-Desktop View:**
![image](https://user-images.githubusercontent.com/15084301/40227449-2ac388ca-5aac-11e8-82d8-0e325898f5ac.png)
**Updated donate page-MobileView:**
![image](https://user-images.githubusercontent.com/15084301/40227500-56189718-5aac-11e8-9974-9c2e9d08fc1d.png)

@viditkothari @strongSoda @mcashashankkumar @utkarsh2102 Please check and let me know your suggestions.

**Comment by strongSoda** [comment]
LGTM

**Comment by mcashashankkumar** [comment]
LGTM

**Comment by gauravsinghaec** [comment]
Thank you all. the changes are deployed to Heroku.
https://jeevanrakht.herokuapp.com/donate

**Comment by gauravsinghaec** [comment]
Issue resolved.
