### ISSUE TITLE
Top Carousel requires relevant images 

### ISSUE THREAD

**Issue by nikki158** [UdacityFrontEndScholarship/jeevan-rakht#242]
![top carousel](https://user-images.githubusercontent.com/35723562/40181350-88286c84-5a06-11e8-9364-8de8f1835f62.png)

`file path : /public/index.html`

**Comment by gauravsinghaec** [comment]
@nikki158 please share your images here with the team.

**Comment by gauravsinghaec** [comment]
@strongSoda @viditkothari please comment on this issue.

**Comment by strongSoda** [comment]
We have got relevant images from @Megha
Hence closing this issue.

**Comment by viditkothari** [comment]
@nikki158 Nice work Namrata! and it seems you adhered to the guides, glad about it too  :)

Thanks

@gauravsinghaec its good to go!

**Comment by viditkothari** [comment]
@strongSoda I really like the second and third. We can include it as another artwork/slide for the carousel.

**Comment by strongSoda** [comment]
Okay go ahead with second and third @vidit @gaurav

**Comment by utkarsh2102** [comment]
Closing this.
This issue has been resolved in PR #245.
Great work @nikki158 :)
