### ISSUE TITLE
login, signup and profile are requesting wrong libraries which does not exists in assets folder.

### ISSUE THREAD

**Issue by computer0101** [UdacityFrontEndScholarship/jeevan-rakht#32]
Following html files are requesting `bootstrap.min.js` and `bootstrap.css` libraries which does not exists in assets folder.
1. login.html
2. signup.html
3. profile.html

Requesting moderators to please have a look at it. 
Thanks,
Devesh Patel (@anonymous)

**Comment by viditkothari** [comment]
@computer0101 We aren't going for dedicated login / signup page.

**Comment by strongSoda** [comment]
Hi @anonymous

Login sign-up would be made using modals, most probably. We have kept those .html files just as an insurance as in future if we want to design the for as entirely new pages we would have the flexibility to do so.

As for profile.html we will have a look into it.

Imran @Jeevan Rakht

**Comment by strongSoda** [comment]
Sorry not @anonymous but @computer0101
