### ISSUE TITLE
Problem with navbar hide on scroll feature

### ISSUE THREAD

**Issue by crisner** [UdacityFrontEndScholarship/jeevan-rakht#38]

**Comment by viditkothari** [comment]
@crisner Can you please elaborate?

**Comment by crisner** [comment]
There was a feature implemented for the fixed navbar to hide upon scrolling which wasn't working. I have submitted a pull request for it.

**Comment by crisner** [comment]
@Soumya44 I have submitted a pull request referencing this issue.
