### ISSUE TITLE
Issue-2 Build the Home page UI

### ISSUE THREAD

**Issue by strongSoda** [UdacityFrontEndScholarship/jeevan-rakht#41]
Hi All!

This is task no. 2.

What you have to do ?

Build the index.html page from the homepage mockup link in the Readme.

Comment your code properly.

While submitting ur PR provide a link to preview ur fork hosted on gh-pages.

We will only consider reviewing ur code if u provide the website link of ur fork.

Deadline:

This Sunday  15 APR.

Get cracking people!!!

**Comment by vivek1996** [comment]
I would like to work on this but I want to know which wireframe is the starting homepage ?

**Comment by Ckbhatia** [comment]
Please be clear & keep updated our classmates on Slack for Project .
it's important to share our work & invite interested classmates to Project .

**Comment by shivendrarox** [comment]
hi @strongSoda and every one, i have designed the query form part of the pdf mockup,
have a look
https://codepen.io/shivendrarox/full/bvPeaZ

**Comment by strongSoda** [comment]
@crisner 

It's Sunday 15 APR . Also updated date in the issue.
