### ISSUE TITLE
Issue-3 : App Design to HTML & CSS

### ISSUE THREAD

**Issue by viditkothari** [UdacityFrontEndScholarship/jeevan-rakht#46]
Hi!

![mockup_app_page_0](https://user-images.githubusercontent.com/409625/38767315-87b4cb0e-3ffc-11e8-838d-42850f48853b.png)

Target file: app.html

Basic overview of the App's structure:

- Header
- - Logo (centered)
- - Profile Avatar/Photo
- BodyContent
- - Button with Label placed above (Locate Blood)
- - Button with Label placed above (Donate Blood)
- Footer
- - Contact #
- - Know More
- - Email ID

The image above is the UI design of the App's first screen. Please note the following:
1. Mark the elements' position
2. Ensure a fluid responsive implementation / HTML
3. Colors: https://github.com/UdacityFrontEndScholarship/jeevan-rakht#color-palette
4. For the icon use FontAwesome
5. The base/background should implement *this specific particle.js* : https://vincentgarreau.com/particles.js/
6. *Include the GitHub pages link to your fork.*

Looking forward to relevant quality contributions by Monday, 17th April, 2018
Vidit @ JeevanRakht

**Comment by SukhjinderArora** [comment]
how will be app.html connected to index.html, as far as I can see index.html is the entry point of the app ?

**Comment by viditkothari** [comment]
@SukhjinderArora 
The project is in two parts:

1. Application : `app.html`
1. Website : `index.html`

`app.html` is linked to `index.html` with the link at the footer: *`Know More`*
and upon launching the site, a person will first be directed to the `app.html`

**Comment by sb39** [comment]
@viditkothari  , the above Ui is already built , or we have to built a copy or similar UI to it ?

**Comment by viditkothari** [comment]
@sb39 This is just visual design, its implementation is what we need. Thus **App Design to HTML & CSS**

**Comment by sb39** [comment]
@viditkothari where you got the img's ? it's not there in the assests fldr

**Comment by viditkothari** [comment]
@sb39  images for? If you need images for icons, instead make use of `Font Awesome` ;)

**Comment by sb39** [comment]
@viditkothari jeevan rakt logo is not font awesome

**Comment by viditkothari** [comment]
@sb39 , go to `assets` folder and find `logo.png`

**Comment by SukhjinderArora** [comment]
@viditkothari do you have SVG format of logo, that would be very small in size and can be increased or decreased in width without distortion?

**Comment by sb39** [comment]
@SukhjinderArora  use font awesome .. for icons

**Comment by viditkothari** [comment]
@SukhjinderArora We can have .svg but for foreseeable future, we don't intend to release the .svg

**Comment by praveen-me** [comment]
Last Date Maybe Tuesday, 17 April.

**Comment by pm17** [comment]
https://readmenow.in/add-particles-js-web-project/ - This could prove helpful for some

**Comment by pm17** [comment]
For particle.JS to work properly, the js files are to be kept in the same folder where the app.html is. Is it fine to work with that?

**Comment by viditkothari** [comment]
@pm17 Did you try using relative path referencing to avoid keeping the `.js` file along with the html ?

**Comment by thisisabdus** [comment]
Not really @pm17. You can put it wherever you want and link it.

**Comment by sb39** [comment]
@viditkothari  how to get the particle js objects. visit the repo and check https://github.com/sb39/started.github.io/
live link = sb39.github.io/started.github.io/

**Comment by pm17** [comment]
@viditkothari I tried

**Comment by praveen-me** [comment]
And I think CDN is better then putting is locally.

**Comment by Monikasumathi** [comment]
@viditkothari where can we get the image for the locate and donate blood?

**Comment by sb39** [comment]
@Monikasumathi they are fontawesome icons, you can search them at -> fontawesome.com/icons

**Comment by souryavaranasi** [comment]
Hi @viditkothari  can I work on this issue or is it assigned to someone?

**Comment by viditkothari** [comment]
Hi @Monikasumathi, as @sb39 said look for the Font Awesome code in the font awesome library :)

**Comment by viditkothari** [comment]
@Souryavaranasi, we will close the issue in few hours. You can continue to contribute after the first pull

**Comment by viditkothari** [comment]
@nsaicharan

**Comment by nsaicharan** [comment]
@viditkothari,
Here's the link - https://rakth-test.herokuapp.com/
