### ISSUE TITLE
Issue-6: Server: Capture the signup details and create user

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/jeevan-rakht#73]
Check below files, and create the signup page template as per wireframe and test the create user flow
**/views/auth/signup.hjs**
Below is the sample route file in project directory
**/routes/auth/signup.js**

See if user exists, if it doesn't make a new one and add user in database
Once successful signed up, we have to perform below actions:
1. Add user in client session and in database
2. Email verified flag will be 'N'
3. On success, redirect to page where he came from.
**Deadline: 26 Apr, 2018**

**Comment by computer0101** [comment]
Hey everyone,
I have tried to implement this issue and below is my github fork link. I would like you all to review it and then if everything works fine and if you ask me to make PR then I will make PR, so that there won't be any unnecessary PR's.
Here is my link to github fork repo:

[https://github.com/computer0101/jeevan-rakht/](https://github.com/computer0101/jeevan-rakht/)

**Comment by gauravsinghaec** [comment]
@computer0101 Hey Devesh, it is much better this time please go ahead and raise the pull request.

**Comment by gauravsinghaec** [comment]
I will add few more fields on the view, hence I am extending the deadline.

**Comment by gauravsinghaec** [comment]
@computer0101 please update the issue once the changes are done as per new fields.

**Comment by computer0101** [comment]
Updated code for capturing signup details as new fields were added on signup page.
Here is my link to github fork repo:
[https://github.com/computer0101/jeevan-rakht/](https://github.com/computer0101/jeevan-rakht/)

Name: Devesh Patel (slack username: @anonymous)

**Comment by gauravsinghaec** [comment]
Hey @computer0101 , now i can see improvement in your coding. Well done!! I can see you are preserving the value of fields as well on error. Good work, please go ahead and raise the PR for this.

**Comment by gauravsinghaec** [comment]
Completed
