### ISSUE TITLE
Issue-7: Server: Login user with email and password

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/jeevan-rakht#74]
Check below files where client side sample HTML is written
**/views/auth/login.hjs**
Below is the sample rout file
**/routes/auth/login.js**
1. Check user validation
2. Allow user login if everything is ok and set the client session.

On successful login, redirect to the page where he came from
**Deadline: 22 Apr,2018**

**Comment by computer0101** [comment]
**Issue 7**
Hello mods and co-mods. I have implemented user signup. 
Please review my code.
Github fork link: [https://github.com/computer0101/jeevan-rakht/](https://github.com/computer0101/jeevan-rakht/)
Heroku Link: [https://sleepy-hamlet-36125.herokuapp.com/](https://sleepy-hamlet-36125.herokuapp.com/)
Name: Devesh Patel (slack username: @anonymous)

**Comment by gauravsinghaec** [comment]
signup or login? @computer0101  :-)

**Comment by computer0101** [comment]
Sorry. Edited. Copied and Pasted previous comment so.. 😄

**Comment by gauravsinghaec** [comment]
Please go ahead and create pull request on the same

**Comment by gauravsinghaec** [comment]
The logic is implemented so closing it.
