### ISSUE TITLE
Issue-8: Design 404, page not found page

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/jeevan-rakht#75]
Update the mentioned file with a creative implementation of 404 error message.
*404 is the page a user sees when he/she either enters wrong URL or there is no file found at the entered URL / endpoint*.
`/views/404.hjs`

Few example 404s:
[Creative 404s](https://www.google.co.in/search?q=creative+404+pages+design&num=20&tbm=isch&source=iu&ictx=1)
[GitHub's 404](https://github.com/viditkotharid)

*Fell free to update the sample template and share with team. Make sure the design aligns well with the brand persona.*

**Comment by vivek1996** [comment]
Can I have the template of the 404 page to work?

**Comment by souryavaranasi** [comment]
Can we design in our own style or there is any template?

**Comment by viditkothari** [comment]
@vivek1996 @souryavaranasi,
Please check the updated information for this issue.

**Comment by Ckbhatia** [comment]
@gauravsingh ! @viditkhothari
Please Check Page 404 Error that I designed . Give Me Some Feedback to Improve it . Thanks

**Comment by seethaR03** [comment]
This is my idea based on existing concept, which I have drawn(excuse the drawing part, as designing was taking too long for me)
![404](https://user-images.githubusercontent.com/27719165/38935747-b95d99e0-433c-11e8-9029-cd103eca517e.jpg)

**Comment by aartigurjar** [comment]
It is important to provide options on 404 page to give directions to visitors on what to do next. Here the page has options like navigating back to Home page, searching a query or visiting the website's social media links. This keeps the visitors to stay on the website.

![404 page mockup](https://user-images.githubusercontent.com/36697551/39110132-c63e15d6-4684-11e8-882d-562a6d0e303e.jpg)

**Comment by viditkothari** [comment]
@seethaR03 good work 😄 
@aartigurjar can you please try for something little more creative?

**Comment by aartigurjar** [comment]
![mockup 2](https://user-images.githubusercontent.com/36697551/39113069-3e197852-468f-11e8-9e51-5945108333a7.jpg)

**Comment by seethaR03** [comment]
@viditkothari  Thanks! Is the final design decided?

**Comment by pm17** [comment]
is this open or final design has been selected?

**Comment by Ckbhatia** [comment]
@gauravsinghaec
I closed the PR , I will Update it Soon & Provide you to Review Before PR . . Thanks For Your Great Support , We have talked more then 1 hour , It was too long & awesome .

**Comment by viditkothari** [comment]
@seethaR03 Hi!, It is still under process :)
@pm17 We are still looking for aesthetically pleasing ones :)

**Comment by Ckbhatia** [comment]
@gauravsinghaec @viditkothari @strongSoda @utkarsh2102 
check this : everything working fine ! contains dual pics . different for mobile view & desktop view .
but different code is added for different image but image is single yet . i am working on it . for Now just check it . if pass then i am going to Make PR .

https://ckbhatia-jeevanrakht-pr.herokuapp.com/j

i hope you will like it & accept my request for PR .

**Comment by vattytrivedi** [comment]
Here I am posting a few pens of the error page, if you like any idea and select it I will merge it with the theme of the page and will raise the PR
- [First](https://codepen.io/VattyTrivedi/pen/VxroRO)
- [Second](https://codepen.io/VattyTrivedi/pen/LmOwaq)
- [Third](https://codepen.io/VattyTrivedi/pen/JvOgze)
- [Fourth](https://codepen.io/VattyTrivedi/pen/PeOMLq)
- [Fifth](https://codepen.io/VattyTrivedi/pen/YLEmBb)
- [Sixth](https://codepen.io/VattyTrivedi/pen/qYVegQ)
- [Seventh](https://codepen.io/VattyTrivedi/pen/QrOeaE)

**Comment by vattytrivedi** [comment]
**Vampire Error Page**
Only CSS used for animation. Feel free to give suggestion for improvement.

[Visit](https://codepen.io/VattyTrivedi/pen/GdyvRY?editors=1000)

**Comment by vattytrivedi** [comment]
Is this issue still open @strongSoda @gauravsinghaec ?

**Comment by gauravsinghaec** [comment]
@vattytrivedi yes

**Comment by vattytrivedi** [comment]
My submission for error page @strongSoda 
Error page #215

**Comment by gauravsinghaec** [comment]
Thank you all @seethaR03 @vivek1996 @Ckbhatia @aartigurjar @vattytrivedi @pm17 for your inputs and here is the page(designed by @vattytrivedi ) which is finalised and deployed on the official site. https://jeevanrakht.herokuapp.com/badpath
![image](https://user-images.githubusercontent.com/15084301/39955624-9c49ade2-55ef-11e8-8aa5-b91f95013985.png)
