### ISSUE TITLE
Issue-9: Server: Email verification implementation

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/jeevan-rakht#77]
In order to implement email verification, you can use node mailer or 
[Sendgrid mailing](https://sendgrid.com/docs/Integrate/Code_Examples/v3_Mail/nodejs.html). 
Below are the required steps:
1. send verification link(with token) to the given email and 
Route files: **routes\profile\verifyemail.js**
2. once user follows the link , verify the token and hence update the flag in database
Route files: **routes\profile\verifyemail_finish.js**
3. Redirect back to profile page of users.

Please check the profile page https://jeevanrakht.herokuapp.com/users where you will get button to verify email. 

Please refer to the RESTApi pdf in README to know more about the API endpoints to be used for the project.

**Deadline : 25 Apr, 2018**

**Comment by kadumuri1994** [comment]
Can I try this one?

**Comment by Hardiki** [comment]
@kadumuri1994 yes you can give it a try..

**Comment by gauravsinghaec** [comment]
@kadumuri1994 Please check the Reset Password code, hope it will help you. Please do let us know if you still want to work on it or shall I assign it to other?

**Comment by gauravsinghaec** [comment]
The task has been completed. We are able to send the verification link. After the link is validated, update the DB to activate the user's account.
