### ISSUE TITLE
Issue-10: Server: Change/Update password Implementation

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/jeevan-rakht#78]
In order to implement forgot/change password functionality, you can use node mailer or 
[Sendgrid mailing](https://sendgrid.com/docs/Integrate/Code_Examples/v3_Mail/nodejs.html). 
Below are the required steps:
1. send password reset link(with token) to the given email and 
Route files: **routes\auth\forgot.js**
2. once user follows the link , take him/her to the reset page to type new password
Route files: **routes\auth\forgot_finish.js**
3. Once user submits new password, update the table to store the hash values for password and redirect back to profile/login page of users wherever he/she came from.

Please check the profile page https://jeevanrakht.herokuapp.com/users where you will get button to change password. You will have the forgot password link in login page as well

Please refer to the RESTApi pdf in README to know more about the API endpoints to be used for the project.

**Deadline : 25 Apr, 2018**

**Comment by gauravsinghaec** [comment]
Added code to send reset password link to registered email and on click of the link. 
Code also validates if the link is valid and if yes then show the page to reset password otherwise redirect to login page.

**Comment by computer0101** [comment]
Implemented update/password issue.
mods and co-mods please review it.
Github fork link: [https://github.com/computer0101/jeevan-rakht/](https://github.com/computer0101/jeevan-rakht/)
Name: Devesh Patel (slack username: @anonymous)

**Comment by gauravsinghaec** [comment]
The task is completed.
