### ISSUE TITLE
Issue-11 Error in the hosted Site

### ISSUE THREAD

**Issue by vivek1996** [UdacityFrontEndScholarship/jeevan-rakht#83]
When the site is visited https://jeevanrakht.herokuapp.com/   the Particle Js is not loaded since it is loaded over HTTP connection .It needed to be changed to HTTPS .Because Chrome blocks the content loaded over HTTP.

**Comment by utkarsh2102** [comment]
Great catch @vivek1996 :)

**Comment by utkarsh2102** [comment]
As this issue has been resolved in #85, I'm closing this.
Great work @nsaicharan :)
