### ISSUE TITLE
Issue-11 : UI Design • Locate Blood • State A

### ISSUE THREAD

**Issue by viditkothari** [UdacityFrontEndScholarship/jeevan-rakht#87]
**Reference: The Wireframe in the README.md**

Target file: *app.html (create a div for the locate blood functionality)*
Source .PSD files:
1. *https://github.com/UdacityFrontEndScholarship/jeevan-rakht/blob/master/public/assets/UI/PSD/MockUp_original.psd* **PSD CC 2018 - with Artboards**
1. *https://github.com/UdacityFrontEndScholarship/jeevan-rakht/blob/master/public/assets/UI/PSD/jeevanrakht-signin-signup%20mock.psd*

Fonts: 
- https://github.com/UdacityFrontEndScholarship/jeevan-rakht/tree/master/public/assets/UI/Fonts

Basic overview of the App's structure:

    Header
        Logo (centered)
        Profile Avatar/Photo
    BodyContent
        <div#StateA>:
            <input> #Search PIN / City
            <dropdown> #BloodGroup
            <dropdown> #radius (range 5km - 50km)
            <input> #when date (default: 2 days)
            <button> Search
    Footer
        Contact #
        Know More
        Email ID

The image above is the UI design of the App's first screen. Please note the following:

    Mark the elements' position
    Ensure a fluid responsive implementation / HTML
    Colors: https://github.com/UdacityFrontEndScholarship/jeevan-rakht#color-palette
    For icons use FontAwesome free library
    The base/background implements this specific particle.js : https://vincentgarreau.com/particles.js/
    Include the GitHub pages link to your fork.

Looking forward to relevant quality contributions by Monday, 21st April, 2018
Vidit @ JeevanRakht

**Comment by benatbanglr369** [comment]
Hi @viditkothari am not able to see the psd file in the first link you provided. The second link shows 404.

**Comment by viditkothari** [comment]
@benatbanglr369 Can you please, clear the cache and try again? I just checked and the first URL seems to work fine. The second URL needed an update and is functional now.
